name: dartssh2_cli
description: The command-line tools built with dartssh2. Includes dartssh and dartsftp.
version: 1.0.0
repository: https://github.com/TerminalStudio/dartssh2_cli

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dartssh2: ^2.7.2
  dart_console: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  dartssh:
  dartsftp:
